# Generated by Django 4.1 on 2022-10-01 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('nombreCompleto', models.CharField(max_length=500, primary_key=True, serialize=False)),
                ('nombreEmpresa', models.CharField(max_length=500)),
                ('Cargo', models.CharField(max_length=500)),
                ('TipodeIndustria', models.CharField(default='Industria', max_length=500)),
                ('tamañodeEmpresa', models.CharField(default='Tamaño de la empresa', max_length=500)),
                ('Telefono', models.CharField(default='Telefono', max_length=100)),
                ('Correo', models.EmailField(max_length=254)),
                ('reto1', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8')], default=1)),
                ('reto2', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8')], default=2)),
                ('Dimension11', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4')], default=1)),
                ('Dimension12', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4')], default=1)),
                ('Dimension21', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4')], default=1)),
                ('Dimension22', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4')], default=1)),
                ('Dimension31', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4')], default=1)),
                ('Dimension32', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4')], default=1)),
                ('Dimension33', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4')], default=1)),
                ('Dimension34', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4')], default=1)),
                ('Dimension35', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4')], default=1)),
                ('Dimension36', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4')], default=1)),
                ('Dimension37', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4')], default=1)),
                ('Dimension38', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4')], default=1)),
                ('NivelIngresos', models.CharField(default='Nivel de ingresos', max_length=500)),
                ('CostoDirectoComoPorcentaje', models.CharField(default='Costo directo como porcentaje', max_length=500)),
                ('CostoDirecto', models.CharField(default='Costo directo', max_length=500)),
                ('valorInventario', models.CharField(default='Valor de inventario', max_length=500)),
            ],
        ),
    ]
