# Generated by Django 4.1 on 2022-09-12 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('nombreCompleto', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('nombreEmpresa', models.CharField(max_length=100)),
                ('Cargo', models.CharField(max_length=100)),
                ('Telefono', models.CharField(max_length=100)),
                ('Correo', models.CharField(max_length=100)),
                ('reto1', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8')], default=1)),
                ('reto2', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8')], default=2)),
                ('Dimension11', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4')], default=1)),
                ('Dimension12', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4')], default=2)),
                ('Dimension21', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4')], default=1)),
                ('Dimension22', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4')], default=2)),
                ('Dimension31', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4')], default=1)),
                ('Dimension32', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4')], default=1)),
                ('Dimension33', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4')], default=1)),
                ('Dimension34', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4')], default=1)),
                ('Dimension35', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4')], default=1)),
                ('Dimension36', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4')], default=1)),
                ('Dimension37', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4')], default=1)),
                ('Dimension38', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4')], default=1)),
                ('NivelIngresos', models.IntegerField(choices=[('1', '1'), ('2', '2'), ('3', '3')], default=2)),
                ('CostoDirectoComoPorcentaje', models.IntegerField(choices=[(10, '10'), (20, '20'), (30, '30'), (40, '40'), (50, '50'), (80, '80')], default=10)),
                ('CostoDirecto', models.BigIntegerField()),
                ('valorInventario', models.IntegerField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4')], default=2)),
            ],
        ),
    ]
