# Generated by Django 4.1 on 2022-10-09 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Madurez40', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='Dimension11',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='Dimension12',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='Dimension21',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='Dimension22',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='Dimension31',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='Dimension32',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='Dimension33',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='Dimension34',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='Dimension35',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='Dimension36',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='Dimension37',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='Dimension38',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='reto1',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='reto2',
            field=models.PositiveIntegerField(default=2),
        ),
    ]
