# Generated by Django 4.1 on 2022-10-11 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Madurez40', '0002_alter_empresa_dimension11_alter_empresa_dimension12_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='reto1',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='reto2',
            field=models.CharField(max_length=1000),
        ),
    ]
