# Generated by Django 4.1 on 2022-10-18 03:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Madurez40', '0003_alter_empresa_reto1_alter_empresa_reto2'),
    ]

    operations = [
        migrations.RenameField(
            model_name='empresa',
            old_name='tamañodeEmpresa',
            new_name='tamanodeEmpresa',
        ),
    ]
