# Generated by Django 4.1 on 2022-10-26 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Madurez40', '0005_alter_empresa_nivelingresos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='CostoDirecto',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='CostoDirectoComoPorcentaje',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='valorInventario',
            field=models.FloatField(default=0),
        ),
    ]
