# Generated by Django 4.1 on 2022-12-05 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Madurez40', '0007_alter_empresa_reto1_alter_empresa_reto2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empresa',
            name='Dimension37',
        ),
        migrations.RemoveField(
            model_name='empresa',
            name='Dimension38',
        ),
    ]
